### ISSUE TITLE
正常启动，但redis出错，无法进行爬虫

### ISSUE THREAD

**Issue by sucof** [howie6879/owllook#17]
如题：python3 server.py出现如下错误：
```
owllook/fetcher/cache.py", line 52, in wrapper
    if await cache_instance.exists(cache_key):
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
......
exists = await redis.exists(key)
AttributeError: 'RedisConnection' object has no attribute 'exists'
```
版本：Python 3.5.2

**Comment by howie6879** [comment]
请问你aiocache版本是？

**Comment by sucof** [comment]
0.3.2，直接通过pip3 install -r requirements.txt安装的 @howie6879

**Comment by howie6879** [comment]
@sucof 是运行server.py文件马上就出这个错误？还是进行什么操作触发了这个错误，我这边没法复现你的bug

**Comment by sucof** [comment]
我的步骤是：

1. git clone https://github.com/howie6879/owllook
2. cd owllook
3. pip3 install -r requirements.txt
4. cd owllook
5. python3 server.py

进入http://127.0.0.1:8001; 就会出现上面的问题，点击排行榜也会出现同样的问题：
```
ERROR root(56) | Unexpected error with RedisCache (localhost:6379)
Traceback (most recent call last):
  File "~owllook/owllook/fetcher/cache.py", line 52, in wrapper
    if await cache_instance.exists(cache_key):
 .....
  File "/usr/local/lib/python3.5/dist-packages/aiocache/backends/redis.py", line 119, in _exists
    exists = await redis.exists(key)
```

**Comment by howie6879** [comment]
可以确定是redis的连接问题：
``` shell
2018-01-15 19:59:21,253 INFO asyncio_redis(99) | Connecting to redis
2018-01-15 19:59:21,273 INFO asyncio_redis(821) | Redis connection made
2018-01-15 19:59:21,282 INFO asyncio_redis(99) | Connecting to redis
2018-01-15 19:59:21,285 INFO asyncio_redis(821) | Redis connection made
2018-01-15 19:59:21,286 INFO asyncio_redis(99) | Connecting to redis
2018-01-15 19:59:21,290 INFO asyncio_redis(821) | Redis connection made
2018-01-15 19:59:21,291 INFO asyncio_redis(99) | Connecting to redis
2018-01-15 19:59:21,299 INFO asyncio_redis(821) | Redis connection made
```` 
你终端有显示redis连接成功的标识么？

**Comment by sucof** [comment]
没有你的这个显示，但是使用redis-cli是能成功连接的：```
redis-cli
127.0.0.1:6379> 
```
同时用pycharm调也没发现redis连接成功或者失败的信息，是不能用默认配置吗？

**Comment by howie6879** [comment]
我这边调试用的默认配置并无问题，目前你提供的消息我给不出解决方案，你可以把你运行到报错的所有log复制上来看看么？

**Comment by sucof** [comment]
使用python3 server.py 后的错误：
```
2018-01-15 20:43:20,589 WARNING aiocache.log(13) | cPickle module not found, using pickle
[2018-01-15 20:43:21 +0800] [7752] [DEBUG] 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

2018-01-15 20:43:21,187 DEBUG root(803) | 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

[2018-01-15 20:43:21 +0800] [7752] [INFO] Goin' Fast @ http://127.0.0.1:8001
2018-01-15 20:43:21,188 INFO root(813) | Goin' Fast @ http://127.0.0.1:8001
2018-01-15 20:43:21,189 INFO root(32) | Starting aiocache
2018-01-15 20:43:21,189 INFO root(43) | Starting redis pool
[2018-01-15 20:43:21 +0800] [7752] [INFO] Starting worker [7752]
2018-01-15 20:43:21,192 INFO root(608) | Starting worker [7752]
2018-01-15 20:43:25,960 ERROR root(56) | Unexpected error with RedisCache (localhost:6379)
Traceback (most recent call last):
  File "owllook/owllook/fetcher/cache.py", line 52, in wrapper
    if await cache_instance.exists(cache_key):
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiocache/cache.py", line 41, in _enabled
    return await fn(*args, **kwargs)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiocache/cache.py", line 31, in _timeout
    return await asyncio.wait_for(fn(self, *args, **kwargs), self.timeout)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/aiocache/cache.py", line 55, in _plugins
    ret = await fn(self, *args, **kwargs)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiocache/cache.py", line 301, in exists
    ret = await self._exists(ns_key)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiocache/backends/redis.py", line 119, in _exists
    exists = await redis.exists(key)
AttributeError: 'RedisConnection' object has no attribute 'exists'
[2018-01-15 20:43:26 +0800] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8001/  200 7287
2018-01-15 20:43:26,023 INFO sanic.access(325) | 
[2018-01-15 20:43:26 +0800] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8001/static/novels/css/main.css  304 0
2018-01-15 20:43:26,088 INFO sanic.access(325) | 
[2018-01-15 20:43:26 +0800] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8001/static/novels/css/index.css  304 0
2018-01-15 20:43:26,092 INFO sanic.access(325) | 
[2018-01-15 20:43:26 +0800] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8001/static/novels/js/main.js  304 0
2018-01-15 20:43:26,105 INFO sanic.access(325) | 
[2018-01-15 20:43:26 +0800] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8001/static/novels/img/logo_home.png  304 0
2018-01-15 20:43:26,234 INFO sanic.access(325) | 
[2018-01-15 20:43:31 +0800] [7752] [INFO] KeepAlive Timeout. Closing connection.
2018-01-15 20:43:31,107 INFO root(193) | KeepAlive Timeout. Closing connection.
[2018-01-15 20:43:31 +0800] [7752] [INFO] KeepAlive Timeout. Closing connection.
2018-01-15 20:43:31,236 INFO root(193) | KeepAlive Timeout. Closing connection.
```

**Comment by howie6879** [comment]
``` python
            try:
                if await cache_instance.exists(cache_key):
                    return await cache_instance.get(cache_key)

            except Exception:
                LOGGER.exception("Unexpected error with %s", cache_instance)
```
我只能说这里出错了，至于为什么出这个错，我也不是很清楚，或许你可以试试连接另外的redis试试看

**Comment by sucof** [comment]
嗯，确实挺奇怪的，我也是一直在调这个提示，请问您的系统版本是哪个？ubuntu16.04，内核是：
`Linux stock 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by howie6879** [comment]
ubuntu系列我都用过，没出现过这问题

**Comment by sucof** [comment]
我试了下面的代码，redis是没问题的：
```
import redis

#print(redis)
r = redis.Redis(
    host='127.0.0.1',
    port=6379, 
    password='')

name="qq"
key="b"
value=10000
#print(r.info())
print(r.hset(name, key, value))
print(r.hget(name,key))
```
```
python3 test1.py 
0
b'10000'
```
所以应该不是redis安装的问题，可能是连接方式的问题

**Comment by howie6879** [comment]
那我也不清楚 实在复现不出来:sob:

**Comment by howie6879** [comment]
那我也不清楚 实在复现不出来:sob:

**Comment by howie6879** [comment]
那我也不清楚 实在复现不出来:sob:

**Comment by howie6879** [comment]
那我也不清楚 实在复现不出来:sob:

**Comment by howie6879** [comment]
那我也不清楚 实在复现不出来:sob

**Comment by sucof** [comment]
哈哈，sorry大大，我再慢慢调下。谢谢 @howie6879

**Comment by sucof** [comment]
@howie6879 试了几个ubuntu新下载的版本，均存在相同问题，python3.5.2，是不是大大用的是anaconda等装的环境，python3.6的版本？写了几个redis的小程序，都是没问题，感觉只有环境不同这个问题了。。。

**Comment by sucof** [comment]
@howie6879 算了，当我没说，安装了最新的干净python3.6环境，错误还是redis出错，放弃了。。

**Comment by howie6879** [comment]
@sucof 你好，我也重新开了一个环境从安装到运行，也没有问题，然后就算你不装redis也报的不是这个错，我觉得是包的问题，要不你试下用docker运行，readme那里有介绍

我在ubuntu14 16 17，centos，win下都运行过owllook，可以再试试

**Comment by sucof** [comment]
如果是包的问题的话，都是用pip3 install -r requirements.txt安装的话，还有种可能就是源不同，有可能使得包的版本不一样，请问您的源是什么？我使用的是http://mirrors.aliyun.com/pypi/simple源

**Comment by howie6879** [comment]
我用清华源 特别的包的版本号 我都做了限制

**Comment by sucof** [comment]
docker开启后会跳到owllook.net，安装aioredis==0.3.2版本能解决我出现的这个问题，但是登陆会有点问题。

**Comment by howie6879** [comment]
说明是包的问题 跳转问题 你配置下 就好

**Comment by howie6879** [comment]
@sucof 你原本版本出错的aioredis是什么版本

**Comment by sucof** [comment]
以前默认安装的是1.0.0版本

**Comment by howie6879** [comment]
好 现在把版本限制下，你问题都解决了吧？

**Comment by sucof** [comment]
嗯，差不多，谢谢，感觉爬虫的配置有点问题，在congfi中没有配置mongodb,配置好后，数据没有写进去，得调试下

**Comment by sucof** [comment]
@howie6879 ，爬数据得时候使用schedule.every(60).minutes.do(start_spider)爬不了数据，我已经改成schedule.every(1).minutes.do(start_spider)了，不明白为什么不在while里的sleep直接使用时间就行了吧（至少我是可以的），比如：
```
while True:
    start_spider()
    schedule.run_pending()
    time.sleep(60)  #时间可设
```
效果是一样的啊，是schedule函数效率高吗？

**Comment by howie6879** [comment]
那是设置多久运行一次爬虫脚本，我原本是60分钟，你改成2分钟了  while下面是循环时间~~你可以看下这个库的用法

**Comment by sucof** [comment]
你可能理解错我的意思了，我不是说使用`schedule.every(1).minutes.do(start_spider)`再用while，这是两分钟，我的意思是只有一个规划，直接使用 while 和 sleep 就可以每隔多长时间进行爬虫了
还有就是我用schedule函数，一直不执行start_spider 😢 ，所以用这个while sleep方法了

**Comment by howie6879** [comment]
time只能执行固定间隔时间的任务，而且它是阻塞的

**Comment by sucof** [comment]
ok，谢谢
