### ISSUE TITLE
pip报错 No matching distribution found for aioredis==0.3.3 (from -r requirements.txt (line 1))

### ISSUE THREAD

**Issue by wxlost** [howie6879/owllook#19]
pip3 install -r requirements.txt
执行报错是哪里错了吗....这个错误我百度谷歌了半天都没找到答案..头疼

![qq 20180219202312](https://user-images.githubusercontent.com/19698455/36377638-cde4c7f6-15b2-11e8-8c26-e335cfa87fa2.png)

**Comment by wxlost** [comment]
[root@MyCloudServer owllook]# pip3 install -vvv -r requirements.txt
Collecting aioredis==0.3.3 (from -r requirements.txt (line 1))
  1 location(s) to search for versions of aioredis:
  * https://pypi.python.org/simple/aioredis/
  Getting page https://pypi.python.org/simple/aioredis/
  Looking up "https://pypi.python.org/simple/aioredis/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Incremented Retry for (url='/simple/aioredis/'): Retry(total=4, connect=None, read=None, redirect=None)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b20914a8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/aioredis/
  Starting new HTTPS connection (2): pypi.python.org
  Incremented Retry for (url='/simple/aioredis/'): Retry(total=3, connect=None, read=None, redirect=None)
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b20912e8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/aioredis/
  Starting new HTTPS connection (3): pypi.python.org
  Incremented Retry for (url='/simple/aioredis/'): Retry(total=2, connect=None, read=None, redirect=None)
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b2091240>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/aioredis/
  Starting new HTTPS connection (4): pypi.python.org
  Incremented Retry for (url='/simple/aioredis/'): Retry(total=1, connect=None, read=None, redirect=None)
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b2091c88>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/aioredis/
  Starting new HTTPS connection (5): pypi.python.org
  Incremented Retry for (url='/simple/aioredis/'): Retry(total=0, connect=None, read=None, redirect=None)
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b2091860>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/aioredis/
  Starting new HTTPS connection (6): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/aioredis/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/aioredis/ (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b20913c8>: Failed to establish a new connection: [Errno -2] Name or service not known',)) - skipping
  Could not find a version that satisfies the requirement aioredis==0.3.3 (from -r requirements.txt (line 1)) (from versions: )
Cleaning up...
No matching distribution found for aioredis==0.3.3 (from -r requirements.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/python3/lib/python3.5/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/python3/lib/python3.5/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for aioredis==0.3.3 (from -r requirements.txt (line 1))
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/python3/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
pip._vendor.requests.packages.urllib3.exceptions.NewConnectionError: <pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b2091c88>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b2091c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/python3/lib/python3.5/site-packages/pip/_vendor/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
pip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90b2091c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by howie6879** [comment]
换国内源

**Comment by wxlost** [comment]
试过了也不行.最后试了下ping.发现无法解析....改了下DNS并且换为国内源可以了~感谢
