### ISSUE TITLE
如果搜索不相关的东西会挂，注册后登录界面点击登录后没有任何反应

### ISSUE THREAD

**Issue by akkuman** [howie6879/owllook#2]
![snipaste_20170527_204131.png](https://ooo.0o0.ooo/2017/05/27/592974271d637.png)

**Comment by howie6879** [comment]
1.你部署的代码版本是最新的么？https://www.owllook.net/search?wd=你哈
你访问上面是没问题的
2.这个问题你确认下mongo的连接吧  部署的官网是没有这个问题的

**Comment by akkuman** [comment]
mongodb安装后我倒是没经过任何配置，只是启动了mongod，
```python
MONGODB = dict(
    HOST="",
    PORT="",
    USERNAME='',
    PASSWORD='',
    DATABASE='owllook',
)
```
这个需要配置吗？

**Comment by akkuman** [comment]
谢谢。我知道了，确实需要配置，现在正常了。十分感谢

**Comment by akkuman** [comment]
配置mongo HOST和PORT之后倒是解决了第一个问题，不过依旧点击登录没反应，

**Comment by howie6879** [comment]
首先你确定下是连接到自己的mongo  然后注册也成功了 再试试登录  最后还是不行的话你就在代码层面调试下 看输出的信息排查错误在哪了

**Comment by akkuman** [comment]
```
2017-05-27 22:19:16 - (network)[INFO][('127.0.0.1:35769',)]: POST b'/operate/login'  408 22
2017-05-27 22:19:16,629 INFO network(298) | 
2017-05-27 22:19:16 - (sanic)[ERROR]: Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sanic/app.py", line 495, in handle_request
    response)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/sanic/app.py", line 621, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "server.py", line 65, in save_session
    await app.session_interface.save(request, response)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/sanic_session/redis_session_interface.py", line 88, in save
    redis_connection = await self.redis_getter()
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/root/owllook/novels_search/database/redis/redisbase.py", line 20, in get_redis_pool
    db=REDIS_DICT.get('SESSION_DB', None)
  File "/usr/local/lib/python3.5/site-packages/asyncio_redis/pool.py", line 63, in create
    protocol_class=protocol_class)
  File "/usr/local/lib/python3.5/site-packages/asyncio_redis/connection.py", line 71, in create
    yield from connection._reconnect()
  File "/usr/local/lib/python3.5/site-packages/asyncio_redis/connection.py", line 111, in _reconnect
    yield from asyncio.sleep(interval, loop=self._loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 524, in sleep
    return (yield from future)
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 96, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108829)
concurrent.futures._base.CancelledError
2017-05-27 22:19:16,630 ERROR sanic(498) | Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sanic/app.py", line 495, in handle_request
    response)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/sanic/app.py", line 621, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "server.py", line 65, in save_session
    await app.session_interface.save(request, response)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/sanic_session/redis_session_interface.py", line 88, in save
    redis_connection = await self.redis_getter()
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 128, in throw
    return self.gen.throw(type, value, traceback)
  File "/root/owllook/novels_search/database/redis/redisbase.py", line 20, in get_redis_pool
    db=REDIS_DICT.get('SESSION_DB', None)
  File "/usr/local/lib/python3.5/site-packages/asyncio_redis/pool.py", line 63, in create
    protocol_class=protocol_class)
  File "/usr/local/lib/python3.5/site-packages/asyncio_redis/connection.py", line 71, in create
    yield from connection._reconnect()
  File "/usr/local/lib/python3.5/site-packages/asyncio_redis/connection.py", line 111, in _reconnect
    yield from asyncio.sleep(interval, loop=self._loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 524, in sleep
    return (yield from future)
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 96, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108829)
concurrent.futures._base.CancelledError
2017-05-27 22:19:16 - (network)[INFO][127.0.0.1:35769]: POST http://127.0.0.1:8001/operate/login  200 12
2017-05-27 22:19:16,630 INFO network(206) | 
2017-05-27 22:20:00 - (sanic)[ERROR]: NoneType: None

2017-05-27 22:20:00,341 ERROR sanic(104) | NoneType: None
```

**Comment by akkuman** [comment]
谢谢指导，我排查到原因了^_^
