### ISSUE TITLE
新的docker镜像无法启动

### ISSUE THREAD

**Issue by pl1612127** [howie6879/owllook#50]
报错信息如下：
`novel    | [2018-12-14 13:31:49,682] 12-INFO log::info():l15: GET: http://r.qidian.com/?chn=1
novel    | [2018-12-14 13:31:49,974] 12-ERROR log::exception():l30: there are no users authenticated
novel    | Traceback (most recent call last):
novel    |   File "/opt/owllook/spiders/qidian_ranking.py", line 93, in save
novel    |     upsert=True)
novel    |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
novel    |     result = self.fn(*self.args, **self.kwargs)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/collection.py", line 995, in update_one
novel    |     session=session),
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/collection.py", line 851, in _update_retryable
novel    |     _update, session)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1243, in _retryable_write
novel    |     return self._retry_with_session(retryable, func, s, None)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1196, in _retry_with_session
novel    |     return func(session, sock_info, retryable)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/collection.py", line 847, in _update
novel    |     retryable_write=retryable_write)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/collection.py", line 817, in _update
novel    |     retryable_write=retryable_write).copy()
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
novel    |     unacknowledged=unacknowledged)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
novel    |     parse_write_concern_error=parse_write_concern_error)
novel    |   File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
novel    |     raise OperationFailure(msg % errmsg, code, response)
novel    | pymongo.errors.OperationFailure: there are no users authenticated
`

建议每次发docker包使用新的tag ，这样可以使用指定的tag运行 ，现在看tag全都是latest

**Comment by howie6879** [comment]
日志：pymongo.errors.OperationFailure: there are no users authenticated
