### ISSUE TITLE
用你公众号上的教程安装，请问，安装好后，访问地址是什么？怎么才能加入系统服务，随机器启动？

### ISSUE THREAD

**Issue by aff2018** [howie6879/owllook#54]
https://mp.weixin.qq.com/s/0CqLiKsyDQ-pVmeo3R-UlA

用你公众号上的教程安装
请问，安装好后，访问地址是什么？
运行owllook：
cd owllook
python run.py
怎么才能加入系统服务，随机器启动？

**Comment by howie6879** [comment]
[cnetos设置服务开机启动](https://www.google.com/search?q=cnetos%E8%AE%BE%E7%BD%AE%E6%9C%8D%E5%8A%A1%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8&oq=cnetos%E8%AE%BE%E7%BD%AE%E6%9C%8D%E5%8A%A1%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8&aqs=chrome..69i57.7135j0j7&sourceid=chrome&ie=UTF-8)

**Comment by aff2018** [comment]
谢谢。
今天在试着装
wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-5.3.0-Linux-x86_64.sh
安装
chmod -R a+x Anaconda3-5.3.0-Linux-x86_64.sh 
./Anaconda3-5.3.0-Linux-x86_64.sh
 刷新终端
这里提示安装
Do you wish to proceed with the installation of Microsoft VSCode? [yes|no]
要装吗？
 创建 Python3.6 环境
conda create -n python36 python=3.6
用上面这句，提示-bash: conda: command not found，这是没有conda这个命令，不知道什么情况？

**Comment by aff2018** [comment]
安装了conda create -n python36 python=3.6
有问题了，我又重新运行了一下：
root@ip-172-26-6-74:~/owllook# conda create -n python36 python=3.6

CondaValueError: prefix already exists: /root/anaconda3/envs/python36

root@ip-172-26-6-74:~/owllook# cd ~/owllook
root@ip-172-26-6-74:~/owllook# pip install pipenv
Requirement already satisfied: pipenv in /root/anaconda3/lib/python3.7/site-packages (2018.11.26)
Requirement already satisfied: setuptools>=36.2.1 in /root/anaconda3/lib/python3.7/site-packages (from pipenv) (40.2.0)
Requirement already satisfied: certifi in /root/anaconda3/lib/python3.7/site-packages (from pipenv) (2018.8.24)
Requirement already satisfied: pip>=9.0.1 in /root/anaconda3/lib/python3.7/site-packages (from pipenv) (19.0)
Requirement already satisfied: virtualenv in /root/anaconda3/lib/python3.7/site-packages (from pipenv) (16.2.0)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /root/anaconda3/lib/python3.7/site-packages (from pipenv) (0.5.0)
root@ip-172-26-6-74:~/owllook# pipenv install --python  /root/anaconda3/envs/python36/bin/python3.6
Traceback (most recent call last):
  File "/root/anaconda3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 494, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 95, in find_python_version
    version_dict = PythonVersion.parse(major)
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 359, in parse
    version_dict = parse_python_version(str(version))
  File "/root/anaconda3/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/utils.py", line 86, in parse_python_version
    raise InvalidPythonVersion("%s is not a python version" % version_str)
pipenv.vendor.pythonfinder.exceptions.InvalidPythonVersion:  /root/anaconda3/envs/python36/bin/python3.6 is not a python version
root@ip-172-26-6-74:~/owllook# pipenv run pip install pip==18.0
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
root@ip-172-26-6-74:~/owllook# pipenv install
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
root@ip-172-26-6-74:~/owllook# 
分明装的3.6，为何，看提示是3.7？且提示Warning: Python 3.6 was not found on your system…

**Comment by aff2018** [comment]
pipenv install运行这个，中间好多错误提示，搞不清楚

**Comment by aff2018** [comment]
#到这里，运行下面这个，算成功还是没成功？访问地址是什么？
[root@ip-172-26-12-56 owllook]# cd owllook
[root@ip-172-26-12-56 owllook]# python run.py
[2019-01-23 02:00:12,685] 1566-INFO __init__::load_config():l24: owllook 启动模式：DEV

Error: class uri 'sanic.worker.GunicornWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/owllook-kjRL-ddR/lib/python3.6/site-packages/gunicorn/util.py", line 135, in load_class
    mod = import_module('.'.join(components))
  File "/root/.local/share/virtualenvs/owllook-kjRL-ddR/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/virtualenvs/owllook-kjRL-ddR/lib/python3.6/site-packages/sanic/__init__.py", line 1, in <module>
    from sanic.app import Sanic
  File "/root/.local/share/virtualenvs/owllook-kjRL-ddR/lib/python3.6/site-packages/sanic/app.py", line 21, in <module>
    from sanic.server import serve, serve_multiple, HttpProtocol, Signal
  File "/root/.local/share/virtualenvs/owllook-kjRL-ddR/lib/python3.6/site-packages/sanic/server.py", line 19, in <module>
    from httptools import HttpRequestParser
ModuleNotFoundError: No module named 'httptools'
]

[root@ip-172-26-12-56 owllook]# [2019-01-23 02:00:13,511] 1566-INFO spider::start():l60: Spider started!
[2019-01-23 02:00:13,513] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=5>
[2019-01-23 02:00:13,521] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=2>
[2019-01-23 02:00:13,521] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=7>
[2019-01-23 02:00:15,769] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=22>
[2019-01-23 02:00:15,839] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=8>
[2019-01-23 02:00:15,840] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=4>
[2019-01-23 02:00:16,702] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=9>
[2019-01-23 02:00:16,759] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=6>
[2019-01-23 02:00:16,793] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=15>
[2019-01-23 02:00:17,673] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=21>
[2019-01-23 02:00:17,742] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=10>
[2019-01-23 02:00:17,743] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=-1>
[2019-01-23 02:00:18,570] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=12>
[2019-01-23 02:00:18,602] 1566-INFO request::current_request_func():l78: <GET: http://r.qidian.com/?chn=1>
[2019-01-23 02:00:19,577] 1566-INFO spider::stop():l139: Stopping spider: ruia
[2019-01-23 02:00:19,578] 1566-INFO spider::start():l84: Total requests: 14
[2019-01-23 02:00:19,578] 1566-INFO spider::start():l87: Time usage: 0:00:06.066820
[2019-01-23 02:00:19,578] 1566-INFO spider::start():l88: Spider finished!
[2019-01-23 02:00:19,579] 1566-INFO spider::start():l60: Spider started!
[2019-01-23 02:00:19,579] 1566-INFO request::current_request_func():l78: <GET: http://book.zongheng.com/rank.html>
[2019-01-23 02:00:20,920] 1566-INFO spider::stop():l139: Stopping spider: ruia
[2019-01-23 02:00:20,920] 1566-INFO spider::start():l84: Total requests: 1
[2019-01-23 02:00:20,921] 1566-INFO spider::start():l87: Time usage: 0:00:01.341586
[2019-01-23 02:00:20,921] 1566-INFO spider::start():l88: Spider finished!

**Comment by aff2018** [comment]
这时用centos7，干净机器弄的，也有状况
cd owllook
python run.py 运行这个，看这个提示，不知道何意

![image](https://user-images.githubusercontent.com/39473264/51579721-fd31c500-1efc-11e9-994d-57b6d687f413.png)
![image](https://user-images.githubusercontent.com/39473264/51579741-07ec5a00-1efd-11e9-8788-44130c8d03e5.png)

**Comment by aff2018** [comment]
算是成功了还是没成功？
浏览器里，用什么地址访问？IP加什么端口？
