### ISSUE TITLE
遇到和之前几位一样的MONGODB后缀问题

### ISSUE THREAD

**Issue by wwfgxnyi** [howie6879/owllook#86]
Traceback (most recent call last):
  File "scheduled_task.py", line 18, in <module>
    from owllook.spiders import QidianRankingSpider, ZHRankingSpider
  File "/root/owllook/owllook/spiders/__init__.py", line 1, in <module>
    from .qidian_ranking import QidianRankingSpider
  File "/root/owllook/owllook/spiders/qidian_ranking.py", line 8, in <module>
    from owllook.database.mongodb import MotorBaseOld
  File "/root/owllook/owllook/database/mongodb/__init__.py", line 1, in <module>
    from .motorbase import MotorBase, MotorBaseOld, PyMongoDb
  File "/root/owllook/owllook/database/mongodb/motorbase.py", line 11, in <module>
    @singleton
  File "/root/owllook/owllook/database/mongodb/motorbase.py", line 19, in MotorBase
    MONGODB = CONFIG.MONGODB
AttributeError: type object 'Config' has no attribute 'MONGODB'

false改了，没用

**Comment by cnmstudio** [comment]
在config目录下建一个proconfig的文件将devconfig.py的内容给复制进去，就行了，
