### ISSUE TITLE
请求服务报错，TypeError: 'Request' object does not support item assignment

### ISSUE THREAD

**Issue by banwang811** [howie6879/owllook#95]
[2020-08-17 19:50:17 +0800] [6338] [INFO] Starting gunicorn 20.0.4
[2020-08-17 19:50:17 +0800] [6338] [INFO] Listening at: http://0.0.0.0:8001 (6338)
[2020-08-17 19:50:17 +0800] [6338] [INFO] Using worker: sanic.worker.GunicornWorker
[2020-08-17 19:50:17 +0800] [6349] [INFO] Booting worker with pid: 6349
2020-08-17 19:50:17,380 WARNING aiocache.log(13) | cPickle module not found, using pickle
[2020-08-17 19:50:17 +0800] [6350] [INFO] Booting worker with pid: 6350
2020-08-17 19:50:17,463 WARNING aiocache.log(13) | cPickle module not found, using pickle
2020-08-17 19:50:17,510 INFO root(25) | owllook 启动模式：PRO
2020-08-17 19:50:17,624 INFO root(25) | owllook 启动模式：PRO
2020-08-17 19:50:18,058 INFO root(27) | Starting aiocache
2020-08-17 19:50:18,058 INFO root(38) | Starting redis pool
2020-08-17 19:50:18,137 INFO root(27) | Starting aiocache
2020-08-17 19:50:18,137 INFO root(38) | Starting redis pool
2020-08-17 19:50:28,549 INFO root(55) | user ip is: None
hello world
2020-08-17 19:50:28,550 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,551 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,551 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,552 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,552 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,553 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,553 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,554 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,554 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,555 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,555 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,556 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,556 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,557 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,557 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,557 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,558 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,558 INFO asyncio_redis(821) | Redis connection made
2020-08-17 19:50:28,559 INFO asyncio_redis(99) | Connecting to redis
2020-08-17 19:50:28,559 INFO asyncio_redis(821) | Redis connection made
[2020-08-17 19:50:28 +0800] [6350] [ERROR] Exception occurred while handling uri: 'http://111.229.35.232:8001/'
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic/app.py", line 907, in handle_request
    request, request_name=name
  File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic/app.py", line 1265, in _run_request_middleware
    response = await response
  File "/soft/owllook/owllook/server.py", line 63, in add_session_to_request
    await app.session_interface.open(request)
  File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic_session/redis_session_interface.py", line 70, in open
    request['session'] = session_dict
TypeError: 'Request' object does not support item assignment
2020-08-17 19:50:28,560 ERROR sanic.root(140) | Exception occurred while handling uri: 'http://111.229.35.232:8001/'
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic/app.py", line 907, in handle_request
    request, request_name=name
  File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic/app.py", line 1265, in _run_request_middleware
    response = await response
  File "/soft/owllook/owllook/server.py", line 63, in add_session_to_request
    await app.session_interface.open(request)
  File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic_session/redis_session_interface.py", line 70, in open
    request['session'] = session_dict
TypeError: 'Request' object does not support item assignment
[2020-08-17 19:50:28 +0800] - (sanic.access)[INFO][119.28.215.114:54176]: GET http://111.229.35.232:8001/  500 250
2020-08-17 19:50:28,563 INFO sanic.access(494) | 
[2020-08-17 19:50:28 +0800] - (sanic.access)[INFO][119.28.215.114:54178]: GET http://111.229.35.232:8001/favicon.ico  200 296
2020-08-17 19:50:28,860 INFO sanic.access(494) |

**Comment by banwang811** [comment]
大佬这个是语法错误吗？

**Comment by banwang811** [comment]
File "/root/.local/share/virtualenvs/owllook-wVMRXxFE/lib/python3.6/site-packages/sanic_session/redis_session_interface.py", line 70, in open
request['session'] = session_dict
TypeError: 'Request' object does not support item assignment

**Comment by banwang811** [comment]
大佬这个是语法错误吗？

**Comment by howie6879** [comment]
应该是你sanic版本不对

2020-08-17 20:30 GMT+08:00, banwang811 <notifications@github.com>:

**Comment by banwang811** [comment]
感谢！是request库的版本太高导致的。
